apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-detection-api
  namespace: oppe2-app
spec:
  replicas: 6
  selector:
    matchLabels:
      app: fraud-detection-api
  template:
    metadata:
      labels:
        app: fraud-detection-api
    spec:
      nodeSelector:
        role: mlops
      # Ensure you have a service account with permissions for Cloud Trace
      serviceAccountName: telemetry-access
      containers:
      - name: fraud-api-container
        image: fraud-app:local
        imagePullPolicy: Never
        command: ["/bin/sh", "-c"]
        args:
        - "pip install opentelemetry-instrumentation-fastapi==0.46b0 && uvicorn app:app --host 0.0.0.0 --port 8001"
        volumeMounts:
        - name: app-py-volume
          mountPath: /app/app.py
          subPath: app.py
        env:
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://signoz-ingester.signoz.svc.cluster.local:4317"
        ports:
        - containerPort: 8001
        readinessProbe:
          httpGet:
            path: /ready_check
            port: 8001
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /live_check
            port: 8001
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          requests:
            cpu: "250m"
            memory: 256Mi
          limits:
            cpu: "250m"
            memory: 256Mi
      volumes:
      - name: app-py-volume
        configMap:
          name: fraud-app-py
