apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlops-workloads
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/Shrinet82/flagship-gitops.git'
    targetRevision: main
    path: manifests/mlops
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: oppe2-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
